version: '3'
services:
   rstudio:
      container_name: ccog-content-media-report
      build: .
      volumes:
         - ../:/home/rstudio/
      environment:
         ADD: shiny
         USER: user
         PASSWORD: password
         ROOT: "TRUE"
      working_dir: /home/rstudio
      entrypoint: /mnt/run_me.sh
      ports:
         - "8787:8787"
         - "3838:3838"